FROM golang:1.24 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /nhp-agent/frpc

ENTRYPOINT ["/nhp-agent/frpc"]
