FROM opennhp-base:latest AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM ubuntu:22.04  AS runtime

COPY --from=building /building/bin/frpc /nhp-agent/frpc

ENTRYPOINT ["/nhp-agent/frpc"]
